# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1glQQ-KWNZ9PoAlpZOFYcYelcZcY5oddi
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from google.colab import files
uploaded = files.upload()
data = pd.read_csv("predictive_maintenance.csv")
data.columns = data.columns.str.strip()
data = data.drop(['UDI', 'Product ID'], axis=1)
data['Type'] = data['Type'].map({'L': 0, 'M': 1, 'H': 2})
target_col = [col for col in data.columns if "failure" in col.lower()][0]
X = data.drop(target_col, axis=1)
y = data[target_col]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
model = Perceptron()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print("Model Accuracy:", accuracy_score(y_test, y_predict))
new_input = pd.DataFrame([X.iloc[0].values], columns=X.columns)
new_data_scaled = scaler.transform(new_input)
prediction = model.predict(new_data_scaled)
print("Prediction:", "Machine Failure" if prediction[0] == 1 else "No Failure")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from google.colab import files
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)
print(df.head())
df = df.dropna()
target_col = "Failure Type"
features = ["Air temperature [K]", "Process temperature [K]", "Rotational speed [rpm]"]
X = df[features].values
y = df[target_col].values
classes = np.unique(y)
class_to_int = {c:i for i,c in enumerate(classes)}
y = np.array([class_to_int[i] for i in y])
print("Classes:", class_to_int)
X = (X - X.mean(axis=0)) / X.std(axis=0)
def step(z):
    return 1 if z > 0 else 0
class OvRPerceptron:
    def __init__(self, lr=0.1, epochs=20):
        self.lr = lr
        self.epochs = epochs
        self.weights = {}
    def train_binary(self, X, y_binary):
        X = np.insert(X, 0, 1, axis=1)
        w = np.zeros(X.shape[1])
        for _ in range(self.epochs):
            j = np.random.randint(len(X))
            pred = step(np.dot(X[j], w))
            w += self.lr * (y_binary[j] - pred) * X[j]
        return w
    def fit(self, X, y):
        self.classes = np.unique(y)
        for c in self.classes:
            y_binary = (y == c).astype(int)
            self.weights[c] = self.train_binary(X, y_binary)
    def predict(self, X):
        X = np.insert(X, 0, 1, axis=1)
        results = []
        for x in X:
            scores = {}
            for c, w in self.weights.items():
                scores[c] = np.dot(x, w)
            results.append(max(scores, key=scores.get))
        return np.array(results)
model = OvRPerceptron(lr=0.1, epochs=30)
model.fit(X, y)
preds = model.predict(X)
accuracy = np.mean(preds == y)
print("Training Accuracy:", accuracy)
new_sample = np.array([400, 330, 2500])
new_sample = (new_sample - X.mean(axis=0)) / X.std(axis=0)
pred = model.predict(new_sample.reshape(1, -1))
print("Predicted Class:", classes[pred[0]])
fig = plt.figure(figsize=(10,7))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(
    X[:,0], X[:,1], X[:,2],
    c=y, cmap='rainbow', s=40)
ax.set_xlabel(features[0])
ax.set_ylabel(features[1])
ax.set_zlabel(features[2])
plt.title("3D View of Predictive Maintenance.")
plt.show()
importance = {}
for c, w in model.weights.items():
    importance[c] = w[1:]
print("Feature Influence:\n")
for c in importance:
    print("\nClass:", classes[c])
    print("Feature weights:", importance[c])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)
df.columns = df.columns.str.strip()
df = df.dropna()
y = df["Target"].values
X = df[["Rotational speed [rpm]", "Torque [Nm]"]].values
X = X.astype(float)
X = (X - X.mean(axis=0)) / X.std(axis=0)
def step(z):
    return 1 if z > 0 else 0
class Perceptron:
    def __init__(self, lr=0.01, epochs=20):
        self.lr = lr
        self.epochs = epochs
    def fit(self, X, y):
        X = np.insert(X, 0, 1, axis=1)
        self.w = np.zeros(X.shape[1])
        for _ in range(self.epochs):
            idx = np.random.permutation(len(X))
            Xs, ys = X[idx], y[idx]
            for xi, target in zip(Xs, ys):
                pred = step(np.dot(xi, self.w))
                self.w += self.lr * (target - pred) * xi
        return self
models = {}
for lr in [0.01, 0.1]:
    model = Perceptron(lr=lr, epochs=20)
    model.fit(X, y)
    models[lr] = model
for lr in [0.01, 0.1]:
    model = models[lr]
    w = model.w
    plt.figure(figsize=(6,5))
    plt.scatter(X[:,0], X[:,1], c=y, cmap="bwr", alpha=0.6)
    x_min, x_max = X[:,0].min(), X[:,0].max()
    xs = np.linspace(x_min, x_max, 100)
    ys = -(w[0] + w[1]*xs) / w[2]
    plt.plot(xs, ys, 'k--', label="Decision Boundary")
    plt.xlabel("Rotational speed [rpm]")
    plt.ylabel("Torque [Nm]")
    plt.title(f"Perceptron (Learning Rate = {lr})")
    plt.legend()
    plt.grid()
    plt.show()