# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whiVY0gMxdJWIRBGsScbujXJTf1U92Fb
"""

import numpy as np
import matplotlib.pyplot as plt
def step_function(x):
  return np.where(x >= 0,1,0)
inputs = np.array([-3.0,-1.0,0.0,2.0,5.0])
output = step_function(inputs)
print("Output After Step Function Applied:",output)
x = np.linspace(-5,5,100)
y = step_function(x)
plt.plot(x, y)
plt.title("Step Function Plotting")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
def relu(x):
  return np.maximum(0, x)
inputs = np.array([-4.0,-2.0,0.0,3.0,5.0])
output = relu(inputs)
print("Output After Relu Function Applied:", output)
x = np.linspace(-5,5,100)
y = relu(x)
plt.plot(x,y)
plt.title("Relu Function Plotting")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
def sigmoid(x):
  return 1/(1+ np.exp(-x))
inputs = np.array([-2.0,0.0,1.0,3.0])
output = sigmoid(inputs)
print("Output After Sigmoid Function Applied:", output)
x = np.linspace(-5,5,100)
y = sigmoid(x)
plt.plot(x,y)
plt.title("Sigmoid function Plotting")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
def tanh(x):
  return np.tanh(x)
inputs = np.array([-1.5,0.0,1.0,2.0])
output = tanh(inputs)
print("Output After Tangent Hyperbolic Function Applied:", output)
x = np.linspace(-5,5,100)
y = tanh(x)
plt.plot(x,y)
plt.title("Tangent Hyperbolic Plotting")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
def leaky_relu(x, alpha=0.1):
  return np.where(x >= 0, x , alpha * x)
inputs = np.array([-3.0,-1.0,0.0,2.0])
output = leaky_relu(inputs)
print("Output After Leaky_Relu Function Applied:" , output)
x = np.linspace(-5,5,100)
y1 = leaky_relu(x, 0.1)
y2 = leaky_relu(x, 0.3)
plt.plot(x,y1,label= "alpha=0.1")
plt.plot(x,y2,label= "alpha=0.3")
plt.legend()
plt.title("Leaky_Relu Function Plotting")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
def softmax(x):
  e_x = np.exp(x)
  return e_x/np.sum(e_x)
inputs = np.array([1.0,2.0,3.0])
output = softmax(inputs)
print("Output After Softmax Function Applied:", output)
print("Sum:" , np.sum(output))

import matplotlib.pyplot as plt
x = np.linspace(-10,10,200)
plt.plot(x,sigmoid(x),label="Sigmoid")
plt.plot(x,tanh(x),label="Tangent Hyperbolic")
plt.plot(x,relu(x),label="Relu")
plt.plot(x,leaky_relu(x),label="Leaky_Relu")
plt.legend()
plt.title("Activation Functions Plotting")
plt.grid()
plt.show()