# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzzRytJnBENwPVQQx4TdwfbEVuq8DVsw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from mpl_toolkits.mplot3d import Axes3D
data = pd.read_csv("penguins_size.csv")
print(data.head())
X = data[['culmen_length_mm',
          'culmen_depth_mm',
          'flipper_length_mm']]
y = data['species']
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
encoder = LabelEncoder()
y = encoder.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1
)
model = Sequential()
model.add(Dense(10, activation='relu', input_dim=3))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    validation_split=0.2,
    verbose=1
)
y_prob = model.predict(X_test)
y_pred = np.argmax(y_prob, axis=1)
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.show()
fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')
scatter = ax.scatter(
    X[:,0],
    X[:,1],
    X[:,2],
    c=y
)
ax.set_xlabel("Culmen Length")
ax.set_ylabel("Culmen Depth")
ax.set_zlabel("Flipper Length")
plt.title("3D Visualization of Penguin Classes")
plt.show()
sample = X_test[0].reshape(1,3)
prediction = model.predict(sample)
predicted_class = np.argmax(prediction)
print("\nPredicted Class:", predicted_class)
print("Actual Class:", y_test[0])